---
title: "Ambiguities/mistakes"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(tidyverse)
library(ggplot2)
library(ggmosaic)
library(ggridges)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# bar version?


```{r}
mtcars %>%
  filter(cyl == 4) %>%
  ggplot( aes(x=mpg)) +
  geom_histogram(binwidth = 1)
```




# Density version
```{r}

ggplot(mtcars, aes(x = cyl)) + 
  geom_density(position = "stack")

ggplot(mtcars, aes(x = mpg, fill = factor(cyl))) + 
  geom_density(position = "stack")

ggplot(mtcars, aes(x = mpg, fill = factor(cyl))) + 
  geom_density() + facet_grid(cyl~ .)

ggplot(mtcars, aes(x = mpg, y = factor(cyl) )) + 
  geom_density_ridges()

# count = density * n
# the one with correct marginal distribution

ggplot(mtcars, aes(x = mpg, y = stat(density * n), fill = factor(cyl))) + 
  geom_density(position = "stack")

# conditional
ggplot(mtcars, aes(x = mpg, y = stat(density * n), fill = factor(cyl))) + 
  geom_density(position = "fill")
```
