---
title: "Bar things"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)


library(devtools)
library(riskyr)
library(rv2)
library(tidyverse)
library(ggplot2)
library(ggridges)
library(scales) 
library(patchwork)
```



```{r}
data(cancer)

```

# Single var


## Discrete

A is the dataset, ___ is the random variable

```{r}
df <- data_frame(A = c(rep("a", 10), rep("b", 5), rep("c", 15)))
```


- More reasonable to have a percent stat that works like this
- Need that _setup_params_ probably

```{r}
# https://stackoverflow.com/questions/24576515/relative-frequencies-proportions-with-dplyr
data <- data.frame(df$A)
data %>%
  count(df.A) %>%
  mutate(prob = n/sum(n)) %>%
  select(-n)
```



```{r}
df %>%
  ggplot() + 
  stat_prob(aes(x = A))
```



```{r}
df %>%
  ggplot() + 
  geom_bar(aes(x = A), stat="prob")
```



## Continuous

From [Extending ggplot](https://cran.r-project.org/web/packages/ggplot2/vignettes/extending-ggplot2.html)

```{r}
ggplot(cancer, aes(x=test, colour = cancer)) + 
  stat_density_common()
```



# Two variables

## Marginal?


```{r}
```

```{r}
plot_1 <- cancer %>%
  ggplot(aes(x = factor(test))) + 
  stat_prob()  +
  ylim(c(0,1))

plot_2 <- cancer %>%
  ggplot(aes(x = factor(cancer))) + 
  stat_prob() + 
  ylim(c(0,1))

plot_1 + plot_2
```

## Conditional


```{r}

```

