---
title: "geom-block"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(tidyverse)
library(grid)
library(ggmosaic)
data(cancer)
happy <- data(happy)
happy <- head(happy, n = 10)
```

# width <- P(A)

- Borrowed from ggmosaic

```{r}
ggplot(data = happy) + 
  geom_bloc(aes(width = P(health), fill = health))
```

# heigh <- P(A)

Doesn't seem to be supported with ggmosaic hmmm


# x <- A, height = P(B|A)

TODO: should it be

x <- A, width <- P(A), height <- P(B|A)

```{r}
ggplot(data = happy) + 
  geom_bloc(aes(width = P(health), height = P(sex | .)))
```
# x <- A, height <- P(B)

```{r}
ggplot(happy) +
  geom_bloc(aes(x = discrete(happy), height = P(sex)))
```


```{r}
# ggplot(data = happy) +
#   geom_mosaic(
#     aes(x = product(happy), 
#         fill=happy, 
#         conds=product(sex))) 
```


# x <- A, height <- P(A)

## continuous

```{r}
ggplot(mtcars) + 
  geom_bloc(aes(x = cyl, height = density(.)))
```

```{r}
ggplot(mtcars) +
  geom_bloc(aes(x = mpg, height = density(cyl, .)))
```


```{r}
ggplot(mtcars) + 
  geom_bloc(aes(x = mpg, height = density(cyl | .)))
```



```{r}

ggplot(mtcars, aes(x = cyl)) + 
  geom_density(position = "stack")

ggplot(mtcars, aes(x = mpg, fill = factor(cyl))) + 
  geom_density(position = "stack")

# count = density * n
# the one with correct marginal distribution

ggplot(mtcars, aes(x = mpg, y = stat(density * n), fill = factor(cyl))) + 
  geom_density(position = "stack")

# conditional
ggplot(mtcars, aes(x = mpg, y = stat(density * n), fill = factor(cyl))) + 
  geom_density(position = "fill")
```








## continuous with binning

- discrete: geom_bar (but can't call it yet)
- continuous: geom_histogram

```{r}
ggplot(data= cancer) + 
  geom_bloc(aes(x = test, 
              height = P(.), # height = P(test)
              fill = (test)))
```


## discrete

geom_bar under the hood

```{r}
ggplot(data= happy) + 
  geom_bloc(aes(x = discrete(sex), 
              height = P(sex|.)))
```

# x <- A, height <- P(B|A) 

```{r}
ggplot(data=happy) + 
  geom_bloc(aes(x = discrete(sex), height = P(happy|.)))
```


```{r}
ggplot(data= happy) +
  geom_bar(aes(x = sex, y = (..count..)/sum(..count..), fill = happy))
```

# y <- A, width <- P(A)

coord flip will do, but....


