---
title: "Icon array"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(magrittr)
library(tidyverse)
library(devtools)
```

And adjust the ggplot theme to not draw a bunch of things we don't need for the risk characterization theaters:

```{r ggplot_theme}
theme_set(theme_minimal() +
    theme(
      panel.grid = element_blank()
    )
  )
```

# The manual way

Starting from code from risk theatre

```{r}
N = 100
width = sqrt(N)
height = sqrt(N)
margin = 0.01

x = seq(0, 1, length.out = width + 1)
y = seq(0, 1, length.out = height + 1)

plan = data.frame(
  xleft = x[-length(x)] + margin,
  xright = x[-1] - margin
)

df <- plan %>%
  group_by(xleft, xright) %>%
  do(
    data.frame(
      ybottom = y[-length(y)] + margin,
      ytop = y[-1] - margin
    )) %>%
  ungroup()

```


```{r}
df %>%
  ggplot(aes(xmin = xleft, xmax = xright, ymin = ybottom, ymax = ytop)) +
  geom_rect(color = "lightsteelblue1", fill = NA, size = 0.5) +
  geom_rect(color = "skyblue1", fill = "skyblue1", data = slice(df,1:11)) +
  geom_rect(color = "chartreuse3", fill = "chartreuse3", data = slice(df,12:25)) +
  coord_fixed()
```

# Custom geom_icon?

```{r}
data("cancer")
```

```{r}
cancer %>%
  ggplot() + 
  geom_icon(aes(x = cancer, color = test)) + 
  # stat_icon(aes(x = test, color = cancer), geom = "icon")+
  coord_fixed() + 
  NULL
```




# Test
```{r}
library(gginnards)
```

```{r}
cancer %>%
  ggplot() + 
  geom_icon(aes(x = P(cancer | test), color = cancer )) + 
  coord_fixed()
```


## Debugging

https://cran.r-project.org/web/packages/gginnards/vignettes/user-guide-1.html

```{r}
str(ggplot(cancer) + 
  geom_icon(aes(x = P(cancer | test))))
```




```{r}
ggplot(cancer, aes(x = P(cancer | test), y = P(cancer | test))) + 
    geom_debug()

```














