---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(tidyverse)
```




# geom_bloc

## product plots

```{r}
ggplot(mtcars) + geom_bloc(aes(width = c(P(cyl))))
```

```{r}
ggplot(mtcars) + geom_bloc(aes(height = c(P(cyl|gear)), x = c(gear)))
```

```{r}
ggplot(mtcars) + geom_bloc(aes(height = c(P(cyl)), x = c(cyl)))
```

```{r}
ggplot(mtcars) + geom_bloc(aes(height = c(P(cyl|gear, carb)), x = c(gear, carb)))
```

```{r}
ggplot(mtcars) + geom_bloc(aes(height = c(P(cyl|gear, carb)), x = c(gear), y=c(carb)))
```

```{r}
ggplot(mtcars) + geom_bloc(aes(height = c(P(gear|carb), P(cyl|gear, carb)), x = c(gear, carb)))
```


## density plots


### P(A|...)

  x <- A
  height <- P(A)

```{r}
ggplot(mtcars) +  geom_bloc(aes(x = c(mpg), height = c(P(mpg)))) 
```

P(A|B)

TODO: this spec is wrong

```{r}
ggplot(mtcars) + geom_bloc(aes(x = c(mpg, cyl), height = c(P(mpg | cyl)), colour = factor(cyl)))
```

  x <- A
  color <- B
  height <- P(A|B)

```{r}
ggplot(mtcars) + geom_bloc(aes(x = c(mpg), height = c(P(mpg | cyl)), color = factor(cyl)))
```


Ridge plots
  
  x <- A
  y <- B
  height <- P(A|B)

```{r}
ggplot(mtcars) + geom_bloc(aes(x = c(mpg), height = c(P(mpg | cyl)), y = c(cyl)))
```

  x <- A
  y <- B
  color <- B
  height <- P(A|B)

```{r}
ggplot(mtcars) + geom_bloc(aes(
  x = c(mpg), 
  y = c(cyl),
  height = c(P(mpg | cyl)),  
  color = factor(cyl)
))
```




more conds

```{r}
ggplot(mtcars) + geom_bloc(aes(x = c(mpg,gear), y = c(cyl), height = c(P(mpg | gear, cyl))))
```

### P(B|A, ...)


```{r}
ggplot(mtcars) + geom_bloc(aes(x = c(mpg), height = c(P(cyl | mpg)), color = factor(cyl)), position = "fill")
```

```{r}
ggplot(mtcars) + geom_bloc(aes(x = c(mpg, gear), height = c(P(cyl | gear,mpg))))
```


### P(B,A,...)

```{r}
ggplot(mtcars) + geom_bloc(aes(x = c(hp), height = c(P(cyl|hp), P(hp)), color = factor(cyl)))
```

```{r}
ggplot(mtcars) + geom_density(aes(x =hp))
```


```{r}
ggplot(mtcars) + geom_bloc(aes(x = c(hp, gear), height = c(P(cyl|hp, gear), P(hp|gear))))
```

TODO: more conds

# geom_icon

Using `geom_bloc` first to get the base partition right

```{r}
ggplot(mtcars) + geom_icon(aes(height = c(P(cyl|gear)), x = c(gear)), stat = "icon")
```

```{r}
ggplot(mtcars) + geom_icon(aes(height = c(P(cyl|gear, vs), P(gear|vs)), x = c(gear, vs)), stat = "icon") +
  coord_fixed()
```

```{r}
ggplot(mtcars) + geom_icon(aes(height = c(P(cyl|carb)), y=c(carb)), stat = "icon")
```


```{r}
ggplot(mtcars) + 
  geom_icon(aes(height = c(P(cyl|gear, vs)), x = c(gear), y=c(vs))) +
  # geom_bloc(aes(height = c(P(cyl|gear, vs)), x = c(gear), y=c(vs))) + 
  coord_fixed()
```


## vspine

```{r}
ggplot(mtcars) + 
  geom_icon(aes(height = c(P(cyl)))) + 
  # geom_bloc(aes(height = c(P(cyl)))) + 
  coord_fixed()
```

## hspine

```{r}
ggplot(mtcars) + 
  geom_icon(aes(width = c(P(cyl)))) + 
  geom_bloc(aes(width = c(P(cyl)))) + 
  coord_fixed()
```

## dotplots

```{r}

```

