---
title: "Viz Replication"
author: "Puhe Liang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(tidyverse)
library(ggplot2)
library(ggridges)
library(scales)
library(productplots)
library(ggmosaic)
```


# <h1> one parameter maps to height </h1>

# <h2> discrete </h2>

# <h3> P(A) </h3>

```{r}
# P(happy) -> height
data(happy)
agg = aggregate(happy$happy, by = list(happy = happy$happy), FUN=length)

p<-ggplot(data=agg, aes(x=happy, y=x)) +
  geom_bar(stat="identity")
p

# P(mpg) -> height
ggplot(mapping = aes(x = mpg)) + 
  geom_density(data = mtcars)
   
# P(happy) -> width
p + coord_flip()

```
# <h3> P(A|.) </h3>

```{r}
# P(happy|health) -> height, it implies health -> x; fill = happy
ggplot(happy) + 
  geom_mosaic(aes(x = product(happy), conds = product(health), fill =happy),
              divider = c("vspine", "hbar"),
              na.rm = TRUE)

#ggplot(data = happy) +
#   geom_mosaic(aes(x = product(happy), fill=happy), na.rm=TRUE) + facet_grid(health~.)


# P(happy|health) -> height, health -> x; happy -> y; fill = happy
# does it make sense?
ggplot(happy) +
  geom_mosaic(aes(x = product(health),
                   fill = happy,
                   conds = product(happy)),
               divider = c("hbar", "vspine"),
              na.rm = TRUE)

# P(happy|health) -> height, health -> x; happy -> x; fill = happy
ggplot(happy) +
  geom_mosaic(aes(x = product(health),
                   fill = happy,
                   conds = product(happy)),
               divider = c("hbar", "hspine"),
              na.rm = TRUE)

# P(happy|age) -> height
ggplot(happy, aes(x = age, y = stat(density * n), fill = happy)) + 
  geom_density(position = "fill")

# P(happy|age) -> height; happy -> y
ggplot(happy, aes(x = age, y = happy, fill=happy)) + geom_density_ridges(scale=1)

```


# <h3> P(A,.) </h3>

```{r}
# P(happy,health) -> height, it implies health -> x; fill = happy
agg = aggregate(happy$happy, by = list(happy = happy$happy, health = happy$health, sex = happy$sex), FUN=length)


ggplot(data=agg, aes(x=health, y=x, fill=happy)) +
  geom_bar(stat="identity")

# P(happy,health) -> height, health -> x; happy -> y; (fill = happy)
ggplot(agg, aes(x = health, y = x, fill=happy)) +
  geom_col() +
  facet_grid(happy~.)

# P(happy,health) -> height, health -> x; happy -> x; (fill = happy)
ggplot(agg, aes(x = health, y = x, fill=happy)) +
  geom_col() +
  facet_grid(.~happy)


# P(happy, age) -> height
ggplot(happy, aes(x = age, y = stat(density * n), fill = factor(happy))) + 
  geom_density(position = "stack")


ggplot(happy, aes(x = age, y = stat(density * n), fill = happy)) + 
  geom_density() + facet_grid(happy~ .)

# P(happy, age) -> height; happy - >y
# failed to figure out

```





# <h1> Two parameter probability </h1>


# <h3> P(A) -> height; P(B) -> height</h3>
```{r}
# P(health) -> height; P(happy) -> height; health -> x
agg = aggregate(happy$happy, by = list(happy = happy$happy, health = happy$health, sex = happy$sex), FUN=length)


ggplot(data=agg, aes(x=health, y=x, fill=happy)) +
  geom_bar(stat="identity")
```


# <h3> P(A) -> height; P(B) -> width</h3>
```{r}
# P(happy) -> height; P(health) -> width; happy -> y; health -> x
detach("package:ggmosaic")
prodplot(happy, ~ happy + health, c("vspine","fluct"))
library(ggmosaic)
```

# <h3> P(A|B) -> height; P(B) -> width</h3>
```{r}
# P(happy|health) -> height; P(health) -> width
ggplot(happy) +
  geom_mosaic(aes(x = product(health), fill = happy), na.rm = TRUE)

```

